[2024-11-04T18:37:51.720+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_pipeline.load_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:37:51.726+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_pipeline.load_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:37:51.726+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-04T18:37:51.735+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_users> on 2024-11-03 00:00:00+00:00
[2024-11-04T18:37:51.738+0000] {standard_task_runner.py:57} INFO - Started process 139 to run task
[2024-11-04T18:37:51.741+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_pipeline', 'load_users', 'scheduled__2024-11-03T00:00:00+00:00', '--job-id', '848', '--raw', '--subdir', 'DAGS_FOLDER/user_pipeline.py', '--cfg-path', '/tmp/tmpultp989l']
[2024-11-04T18:37:51.741+0000] {standard_task_runner.py:85} INFO - Job 848: Subtask load_users
[2024-11-04T18:37:51.775+0000] {task_command.py:415} INFO - Running <TaskInstance: user_pipeline.load_users scheduled__2024-11-03T00:00:00+00:00 [running]> on host 2b06df56fdc4
[2024-11-04T18:37:51.821+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_pipeline' AIRFLOW_CTX_TASK_ID='load_users' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T00:00:00+00:00'
[2024-11-04T18:37:51.828+0000] {logging_mixin.py:151} INFO - Usuarios recibidos para cargar: [{'id': 1, 'full_name': 'John Doe', 'email': 'john.doe@example.com', 'age': 30}, {'id': 2, 'full_name': 'Jane Smith', 'email': 'jane.smith@example.com', 'age': 25}, {'id': 3, 'full_name': 'Alice Johnson', 'email': 'alice.johnson@example.com', 'age': 28}]
[2024-11-04T18:37:51.831+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/user_pipeline.py", line 77, in load_users
    cursor.execute(insert_query, (user['id'], user['full_name'], user['email'], user['age']))
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-11-04T18:37:51.838+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=user_pipeline, task_id=load_users, execution_date=20241103T000000, start_date=20241104T183751, end_date=20241104T183751
[2024-11-04T18:37:51.870+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 848 for task load_users (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 139)
[2024-11-04T18:37:51.914+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-04T18:37:51.940+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-04T18:48:50.693+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_pipeline.load_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:48:50.699+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_pipeline.load_users scheduled__2024-11-03T00:00:00+00:00 [queued]>
[2024-11-04T18:48:50.699+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-11-04T18:48:50.709+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_users> on 2024-11-03 00:00:00+00:00
[2024-11-04T18:48:50.714+0000] {standard_task_runner.py:57} INFO - Started process 159 to run task
[2024-11-04T18:48:50.716+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'user_pipeline', 'load_users', 'scheduled__2024-11-03T00:00:00+00:00', '--job-id', '860', '--raw', '--subdir', 'DAGS_FOLDER/user_pipeline.py', '--cfg-path', '/tmp/tmpueq4k4ay']
[2024-11-04T18:48:50.717+0000] {standard_task_runner.py:85} INFO - Job 860: Subtask load_users
[2024-11-04T18:48:50.752+0000] {task_command.py:415} INFO - Running <TaskInstance: user_pipeline.load_users scheduled__2024-11-03T00:00:00+00:00 [running]> on host 9b393f9117ee
[2024-11-04T18:48:50.805+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='user_pipeline' AIRFLOW_CTX_TASK_ID='load_users' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T00:00:00+00:00'
[2024-11-04T18:48:50.814+0000] {logging_mixin.py:151} INFO - Usuarios recibidos para cargar: [{'id': 1, 'full_name': 'John Doe', 'email': 'john.doe@example.com', 'age': 30}, {'id': 2, 'full_name': 'Jane Smith', 'email': 'jane.smith@example.com', 'age': 25}, {'id': 3, 'full_name': 'Alice Johnson', 'email': 'alice.johnson@example.com', 'age': 28}]
[2024-11-04T18:48:50.820+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-11-04T18:48:50.826+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=user_pipeline, task_id=load_users, execution_date=20241103T000000, start_date=20241104T184850, end_date=20241104T184850
[2024-11-04T18:48:50.849+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-04T18:48:50.860+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
